import type { Article } from "@/data/guides/articles/types";

/**
 * Serialize an Article object to a copy-paste-ready TypeScript source file.
 */
export function articleToTsCode(article: Article): string {
  const varName = article.slug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
  const json = JSON.stringify(article, null, 2);
  return `import type { Article } from "./types";

// Auto-generated by AI Content Studio. Review before committing.
export const ${varName}: Article = ${json};
`;
}

export function downloadTsFile(slug: string, code: string): void {
  const blob = new Blob([code], { type: "text/typescript;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slug}.ts`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
