/**
 * Swedish municipality tax table lookup 2026
 * Source: Skatteverket - skattesatser-kommuner-2026.txt
 * Skattetabell = avrundad summa exkl. kyrkoavgift
 */

export interface KommunSkattInfo {
  kommunnamn: string;
  skattetabell: number;
  defaultKolumn: number;
  kommunalskatt: number;
}

export const KOMMUN_SKATT_2026: Record<string, KommunSkattInfo> = {
  "Ale": { kommunnamn: "Ale", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.09 },
  "Alingsås": { kommunnamn: "Alingsås", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.13 },
  "Alvesta": { kommunnamn: "Alvesta", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.71 },
  "Aneby": { kommunnamn: "Aneby", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.14 },
  "Arboga": { kommunnamn: "Arboga", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.58 },
  "Arjeplog": { kommunnamn: "Arjeplog", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.13 },
  "Arvidsjaur": { kommunnamn: "Arvidsjaur", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.43 },
  "Arvika": { kommunnamn: "Arvika", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.32 },
  "Askersund": { kommunnamn: "Askersund", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.44 },
  "Avesta": { kommunnamn: "Avesta", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.24 },
  "Bengtsfors": { kommunnamn: "Bengtsfors", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.69 },
  "Berg": { kommunnamn: "Berg", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.51 },
  "Bjurholm": { kommunnamn: "Bjurholm", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.29 },
  "Bjuv": { kommunnamn: "Bjuv", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.46 },
  "Boden": { kommunnamn: "Boden", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.23 },
  "Bollebygd": { kommunnamn: "Bollebygd", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.36 },
  "Bollnäs": { kommunnamn: "Bollnäs", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.66 },
  "Borgholm": { kommunnamn: "Borgholm", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.73 },
  "Borlänge": { kommunnamn: "Borlänge", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.69 },
  "Borås": { kommunnamn: "Borås", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.08 },
  "Botkyrka": { kommunnamn: "Botkyrka", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.52 },
  "Boxholm": { kommunnamn: "Boxholm", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.66 },
  "Bromölla": { kommunnamn: "Bromölla", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.03 },
  "Bräcke": { kommunnamn: "Bräcke", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.38 },
  "Burlöv": { kommunnamn: "Burlöv", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.56 },
  "Båstad": { kommunnamn: "Båstad", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.70 },
  "Dals-Ed": { kommunnamn: "Dals-Ed", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.98 },
  "Danderyd": { kommunnamn: "Danderyd", skattetabell: 31, defaultKolumn: 1, kommunalskatt: 30.87 },
  "Degerfors": { kommunnamn: "Degerfors", skattetabell: 36, defaultKolumn: 1, kommunalskatt: 35.59 },
  "Dorotea": { kommunnamn: "Dorotea", skattetabell: 36, defaultKolumn: 1, kommunalskatt: 35.94 },
  "Eda": { kommunnamn: "Eda", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.84 },
  "Ekerö": { kommunnamn: "Ekerö", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.74 },
  "Eksjö": { kommunnamn: "Eksjö", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.31 },
  "Emmaboda": { kommunnamn: "Emmaboda", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.11 },
  "Enköping": { kommunnamn: "Enköping", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.34 },
  "Eskilstuna": { kommunnamn: "Eskilstuna", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.14 },
  "Eslöv": { kommunnamn: "Eslöv", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.01 },
  "Essunga": { kommunnamn: "Essunga", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.34 },
  "Fagersta": { kommunnamn: "Fagersta", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.28 },
  "Falkenberg": { kommunnamn: "Falkenberg", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.79 },
  "Falköping": { kommunnamn: "Falköping", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.72 },
  "Falun": { kommunnamn: "Falun", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.34 },
  "Filipstad": { kommunnamn: "Filipstad", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.84 },
  "Finspång": { kommunnamn: "Finspång", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.99 },
  "Flen": { kommunnamn: "Flen", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.39 },
  "Forshaga": { kommunnamn: "Forshaga", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.92 },
  "Färgelanda": { kommunnamn: "Färgelanda", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.68 },
  "Gagnef": { kommunnamn: "Gagnef", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.56 },
  "Gislaved": { kommunnamn: "Gislaved", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.04 },
  "Gnesta": { kommunnamn: "Gnesta", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.24 },
  "Gnosjö": { kommunnamn: "Gnosjö", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.29 },
  "Gotland": { kommunnamn: "Gotland", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.89 },
  "Grums": { kommunnamn: "Grums", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.07 },
  "Grästorp": { kommunnamn: "Grästorp", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.76 },
  "Gullspång": { kommunnamn: "Gullspång", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.26 },
  "Gällivare": { kommunnamn: "Gällivare", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.18 },
  "Gävle": { kommunnamn: "Gävle", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.06 },
  "Göteborg": { kommunnamn: "Göteborg", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.89 },
  "Götene": { kommunnamn: "Götene", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.89 },
  "Habo": { kommunnamn: "Habo", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.22 },
  "Hagfors": { kommunnamn: "Hagfors", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.59 },
  "Hallsberg": { kommunnamn: "Hallsberg", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.14 },
  "Hallstahammar": { kommunnamn: "Hallstahammar", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.98 },
  "Halmstad": { kommunnamn: "Halmstad", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.67 },
  "Hammarö": { kommunnamn: "Hammarö", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.34 },
  "Haninge": { kommunnamn: "Haninge", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.57 },
  "Haparanda": { kommunnamn: "Haparanda", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.13 },
  "Heby": { kommunnamn: "Heby", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.50 },
  "Hedemora": { kommunnamn: "Hedemora", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.44 },
  "Helsingborg": { kommunnamn: "Helsingborg", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.68 },
  "Herrljunga": { kommunnamn: "Herrljunga", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.91 },
  "Hjo": { kommunnamn: "Hjo", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.77 },
  "Hofors": { kommunnamn: "Hofors", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.66 },
  "Huddinge": { kommunnamn: "Huddinge", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.00 },
  "Hudiksvall": { kommunnamn: "Hudiksvall", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.41 },
  "Hultsfred": { kommunnamn: "Hultsfred", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.06 },
  "Hylte": { kommunnamn: "Hylte", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.14 },
  "Hällefors": { kommunnamn: "Hällefors", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.64 },
  "Härjedalen": { kommunnamn: "Härjedalen", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.46 },
  "Härnösand": { kommunnamn: "Härnösand", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.92 },
  "Härryda": { kommunnamn: "Härryda", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.27 },
  "Hässleholm": { kommunnamn: "Hässleholm", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.67 },
  "Håbo": { kommunnamn: "Håbo", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.59 },
  "Höganäs": { kommunnamn: "Höganäs", skattetabell: 31, defaultKolumn: 1, kommunalskatt: 31.20 },
  "Högsby": { kommunnamn: "Högsby", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.36 },
  "Hörby": { kommunnamn: "Hörby", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.55 },
  "Höör": { kommunnamn: "Höör", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.92 },
  "Jokkmokk": { kommunnamn: "Jokkmokk", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.58 },
  "Järfälla": { kommunnamn: "Järfälla", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.81 },
  "Jönköping": { kommunnamn: "Jönköping", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.69 },
  "Kalix": { kommunnamn: "Kalix", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.18 },
  "Kalmar": { kommunnamn: "Kalmar", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.96 },
  "Karlsborg": { kommunnamn: "Karlsborg", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.09 },
  "Karlshamn": { kommunnamn: "Karlshamn", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.09 },
  "Karlskoga": { kommunnamn: "Karlskoga", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.59 },
  "Karlskrona": { kommunnamn: "Karlskrona", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.98 },
  "Karlstad": { kommunnamn: "Karlstad", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.84 },
  "Katrineholm": { kommunnamn: "Katrineholm", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.24 },
  "Kil": { kommunnamn: "Kil", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.92 },
  "Kinda": { kommunnamn: "Kinda", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.29 },
  "Kiruna": { kommunnamn: "Kiruna", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.68 },
  "Klippan": { kommunnamn: "Klippan", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.22 },
  "Knivsta": { kommunnamn: "Knivsta", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.91 },
  "Kramfors": { kommunnamn: "Kramfors", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.72 },
  "Kristianstad": { kommunnamn: "Kristianstad", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.93 },
  "Kristinehamn": { kommunnamn: "Kristinehamn", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.54 },
  "Krokom": { kommunnamn: "Krokom", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.16 },
  "Kumla": { kommunnamn: "Kumla", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.13 },
  "Kungsbacka": { kommunnamn: "Kungsbacka", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.87 },
  "Kungsör": { kommunnamn: "Kungsör", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.20 },
  "Kungälv": { kommunnamn: "Kungälv", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.21 },
  "Kävlinge": { kommunnamn: "Kävlinge", skattetabell: 30, defaultKolumn: 1, kommunalskatt: 29.88 },
  "Köping": { kommunnamn: "Köping", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.33 },
  "Laholm": { kommunnamn: "Laholm", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.09 },
  "Landskrona": { kommunnamn: "Landskrona", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.71 },
  "Laxå": { kommunnamn: "Laxå", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.29 },
  "Lekeberg": { kommunnamn: "Lekeberg", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.02 },
  "Leksand": { kommunnamn: "Leksand", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.09 },
  "Lerum": { kommunnamn: "Lerum", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.32 },
  "Lessebo": { kommunnamn: "Lessebo", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.10 },
  "Lidingö": { kommunnamn: "Lidingö", skattetabell: 30, defaultKolumn: 1, kommunalskatt: 29.96 },
  "Lidköping": { kommunnamn: "Lidköping", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.03 },
  "Lilla Edet": { kommunnamn: "Lilla Edet", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.14 },
  "Lindesberg": { kommunnamn: "Lindesberg", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.89 },
  "Linköping": { kommunnamn: "Linköping", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.04 },
  "Ljungby": { kommunnamn: "Ljungby", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.36 },
  "Ljusdal": { kommunnamn: "Ljusdal", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.16 },
  "Ljusnarsberg": { kommunnamn: "Ljusnarsberg", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.09 },
  "Lomma": { kommunnamn: "Lomma", skattetabell: 31, defaultKolumn: 1, kommunalskatt: 31.01 },
  "Ludvika": { kommunnamn: "Ludvika", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.34 },
  "Luleå": { kommunnamn: "Luleå", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.13 },
  "Lund": { kommunnamn: "Lund", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.71 },
  "Lycksele": { kommunnamn: "Lycksele", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.19 },
  "Lysekil": { kommunnamn: "Lysekil", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.23 },
  "Malmö": { kommunnamn: "Malmö", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.71 },
  "Malung-Sälen": { kommunnamn: "Malung-Sälen", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.74 },
  "Malå": { kommunnamn: "Malå", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.49 },
  "Mariestad": { kommunnamn: "Mariestad", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.03 },
  "Mark": { kommunnamn: "Mark", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.28 },
  "Markaryd": { kommunnamn: "Markaryd", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.60 },
  "Mellerud": { kommunnamn: "Mellerud", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.37 },
  "Mjölby": { kommunnamn: "Mjölby", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.74 },
  "Mora": { kommunnamn: "Mora", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.61 },
  "Motala": { kommunnamn: "Motala", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.54 },
  "Mullsjö": { kommunnamn: "Mullsjö", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.39 },
  "Munkedal": { kommunnamn: "Munkedal", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.15 },
  "Munkfors": { kommunnamn: "Munkfors", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.59 },
  "Mölndal": { kommunnamn: "Mölndal", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.28 },
  "Mönsterås": { kommunnamn: "Mönsterås", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.36 },
  "Mörbylånga": { kommunnamn: "Mörbylånga", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.36 },
  "Nacka": { kommunnamn: "Nacka", skattetabell: 30, defaultKolumn: 1, kommunalskatt: 30.40 },
  "Nora": { kommunnamn: "Nora", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.84 },
  "Norberg": { kommunnamn: "Norberg", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.83 },
  "Nordanstig": { kommunnamn: "Nordanstig", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.31 },
  "Nordmaling": { kommunnamn: "Nordmaling", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.39 },
  "Norrköping": { kommunnamn: "Norrköping", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.59 },
  "Norrtälje": { kommunnamn: "Norrtälje", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.34 },
  "Norsjö": { kommunnamn: "Norsjö", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.49 },
  "Nybro": { kommunnamn: "Nybro", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.48 },
  "Nykvarn": { kommunnamn: "Nykvarn", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.59 },
  "Nyköping": { kommunnamn: "Nyköping", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.54 },
  "Nynäshamn": { kommunnamn: "Nynäshamn", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.47 },
  "Nässjö": { kommunnamn: "Nässjö", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.59 },
  "Ockelbo": { kommunnamn: "Ockelbo", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.56 },
  "Olofström": { kommunnamn: "Olofström", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.04 },
  "Orsa": { kommunnamn: "Orsa", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.59 },
  "Orust": { kommunnamn: "Orust", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.98 },
  "Osby": { kommunnamn: "Osby", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.28 },
  "Oskarshamn": { kommunnamn: "Oskarshamn", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.50 },
  "Ovanåker": { kommunnamn: "Ovanåker", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.66 },
  "Oxelösund": { kommunnamn: "Oxelösund", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.34 },
  "Pajala": { kommunnamn: "Pajala", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.03 },
  "Partille": { kommunnamn: "Partille", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.65 },
  "Perstorp": { kommunnamn: "Perstorp", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.28 },
  "Piteå": { kommunnamn: "Piteå", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.88 },
  "Ragunda": { kommunnamn: "Ragunda", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.21 },
  "Robertsfors": { kommunnamn: "Robertsfors", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.29 },
  "Ronneby": { kommunnamn: "Ronneby", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.97 },
  "Rättvik": { kommunnamn: "Rättvik", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.09 },
  "Sala": { kommunnamn: "Sala", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.48 },
  "Salem": { kommunnamn: "Salem", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.29 },
  "Sandviken": { kommunnamn: "Sandviken", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.41 },
  "Sigtuna": { kommunnamn: "Sigtuna", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.12 },
  "Simrishamn": { kommunnamn: "Simrishamn", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.98 },
  "Sjöbo": { kommunnamn: "Sjöbo", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.39 },
  "Skara": { kommunnamn: "Skara", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.67 },
  "Skellefteå": { kommunnamn: "Skellefteå", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.74 },
  "Skinnskatteberg": { kommunnamn: "Skinnskatteberg", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.63 },
  "Skurup": { kommunnamn: "Skurup", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.89 },
  "Skövde": { kommunnamn: "Skövde", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.38 },
  "Smedjebacken": { kommunnamn: "Smedjebacken", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.73 },
  "Sollefteå": { kommunnamn: "Sollefteå", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.97 },
  "Sollentuna": { kommunnamn: "Sollentuna", skattetabell: 31, defaultKolumn: 1, kommunalskatt: 30.74 },
  "Solna": { kommunnamn: "Solna", skattetabell: 30, defaultKolumn: 1, kommunalskatt: 29.99 },
  "Sorsele": { kommunnamn: "Sorsele", skattetabell: 36, defaultKolumn: 1, kommunalskatt: 35.74 },
  "Sotenäs": { kommunnamn: "Sotenäs", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.76 },
  "Staffanstorp": { kommunnamn: "Staffanstorp", skattetabell: 30, defaultKolumn: 1, kommunalskatt: 30.41 },
  "Stenungsund": { kommunnamn: "Stenungsund", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.41 },
  "Stockholm": { kommunnamn: "Stockholm", skattetabell: 31, defaultKolumn: 1, kommunalskatt: 30.62 },
  "Storfors": { kommunnamn: "Storfors", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.27 },
  "Storuman": { kommunnamn: "Storuman", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.24 },
  "Strängnäs": { kommunnamn: "Strängnäs", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.79 },
  "Strömstad": { kommunnamn: "Strömstad", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.68 },
  "Strömsund": { kommunnamn: "Strömsund", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.21 },
  "Sundbyberg": { kommunnamn: "Sundbyberg", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.87 },
  "Sundsvall": { kommunnamn: "Sundsvall", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.17 },
  "Sunne": { kommunnamn: "Sunne", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.04 },
  "Surahammar": { kommunnamn: "Surahammar", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.48 },
  "Svalöv": { kommunnamn: "Svalöv", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.21 },
  "Svedala": { kommunnamn: "Svedala", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.71 },
  "Svenljunga": { kommunnamn: "Svenljunga", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.82 },
  "Säffle": { kommunnamn: "Säffle", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.09 },
  "Säter": { kommunnamn: "Säter", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.59 },
  "Sävsjö": { kommunnamn: "Sävsjö", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.97 },
  "Söderhamn": { kommunnamn: "Söderhamn", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.46 },
  "Söderköping": { kommunnamn: "Söderköping", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.82 },
  "Södertälje": { kommunnamn: "Södertälje", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.67 },
  "Sölvesborg": { kommunnamn: "Sölvesborg", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.15 },
  "Tanum": { kommunnamn: "Tanum", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.33 },
  "Tibro": { kommunnamn: "Tibro", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.48 },
  "Tidaholm": { kommunnamn: "Tidaholm", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.84 },
  "Tierp": { kommunnamn: "Tierp", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.29 },
  "Timrå": { kommunnamn: "Timrå", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.67 },
  "Tingsryd": { kommunnamn: "Tingsryd", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.29 },
  "Tjörn": { kommunnamn: "Tjörn", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.48 },
  "Tomelilla": { kommunnamn: "Tomelilla", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.08 },
  "Torsby": { kommunnamn: "Torsby", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.59 },
  "Torsås": { kommunnamn: "Torsås", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.08 },
  "Tranemo": { kommunnamn: "Tranemo", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.27 },
  "Tranås": { kommunnamn: "Tranås", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.05 },
  "Trelleborg": { kommunnamn: "Trelleborg", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.87 },
  "Trollhättan": { kommunnamn: "Trollhättan", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.13 },
  "Trosa": { kommunnamn: "Trosa", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.32 },
  "Tyresö": { kommunnamn: "Tyresö", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.12 },
  "Täby": { kommunnamn: "Täby", skattetabell: 30, defaultKolumn: 1, kommunalskatt: 30.17 },
  "Töreboda": { kommunnamn: "Töreboda", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.49 },
  "Uddevalla": { kommunnamn: "Uddevalla", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.93 },
  "Ulricehamn": { kommunnamn: "Ulricehamn", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 32.82 },
  "Umeå": { kommunnamn: "Umeå", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.94 },
  "Upplands Väsby": { kommunnamn: "Upplands Väsby", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.04 },
  "Upplands-Bro": { kommunnamn: "Upplands-Bro", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.02 },
  "Uppsala": { kommunnamn: "Uppsala", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.14 },
  "Uppvidinge": { kommunnamn: "Uppvidinge", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.09 },
  "Vadstena": { kommunnamn: "Vadstena", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.64 },
  "Vaggeryd": { kommunnamn: "Vaggeryd", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.54 },
  "Valdemarsvik": { kommunnamn: "Valdemarsvik", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.32 },
  "Vallentuna": { kommunnamn: "Vallentuna", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.52 },
  "Vansbro": { kommunnamn: "Vansbro", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.57 },
  "Vara": { kommunnamn: "Vara", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.54 },
  "Varberg": { kommunnamn: "Varberg", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.02 },
  "Vaxholm": { kommunnamn: "Vaxholm", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.92 },
  "Vellinge": { kommunnamn: "Vellinge", skattetabell: 30, defaultKolumn: 1, kommunalskatt: 29.97 },
  "Vetlanda": { kommunnamn: "Vetlanda", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.06 },
  "Vilhelmina": { kommunnamn: "Vilhelmina", skattetabell: 36, defaultKolumn: 1, kommunalskatt: 35.79 },
  "Vimmerby": { kommunnamn: "Vimmerby", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.51 },
  "Vindeln": { kommunnamn: "Vindeln", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.49 },
  "Vingåker": { kommunnamn: "Vingåker", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.79 },
  "Vänersborg": { kommunnamn: "Vänersborg", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.98 },
  "Vännäs": { kommunnamn: "Vännäs", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.49 },
  "Värmdö": { kommunnamn: "Värmdö", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.60 },
  "Värnamo": { kommunnamn: "Värnamo", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.57 },
  "Västervik": { kommunnamn: "Västervik", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.31 },
  "Västerås": { kommunnamn: "Västerås", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.53 },
  "Växjö": { kommunnamn: "Växjö", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.48 },
  "Vårgårda": { kommunnamn: "Vårgårda", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.38 },
  "Ydre": { kommunnamn: "Ydre", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.39 },
  "Ystad": { kommunnamn: "Ystad", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.58 },
  "Älmhult": { kommunnamn: "Älmhult", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.15 },
  "Älvdalen": { kommunnamn: "Älvdalen", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 35.06 },
  "Älvkarleby": { kommunnamn: "Älvkarleby", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.69 },
  "Älvsbyn": { kommunnamn: "Älvsbyn", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.08 },
  "Ängelholm": { kommunnamn: "Ängelholm", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.64 },
  "Åmål": { kommunnamn: "Åmål", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.23 },
  "Ånge": { kommunnamn: "Ånge", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.91 },
  "Åre": { kommunnamn: "Åre", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.21 },
  "Årjäng": { kommunnamn: "Årjäng", skattetabell: 35, defaultKolumn: 1, kommunalskatt: 34.54 },
  "Åsele": { kommunnamn: "Åsele", skattetabell: 36, defaultKolumn: 1, kommunalskatt: 35.74 },
  "Åstorp": { kommunnamn: "Åstorp", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 31.76 },
  "Åtvidaberg": { kommunnamn: "Åtvidaberg", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.23 },
  "Öckerö": { kommunnamn: "Öckerö", skattetabell: 33, defaultKolumn: 1, kommunalskatt: 33.33 },
  "Ödeshög": { kommunnamn: "Ödeshög", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.24 },
  "Örebro": { kommunnamn: "Örebro", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.94 },
  "Örkelljunga": { kommunnamn: "Örkelljunga", skattetabell: 31, defaultKolumn: 1, kommunalskatt: 30.53 },
  "Örnsköldsvik": { kommunnamn: "Örnsköldsvik", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.14 },
  "Östersund": { kommunnamn: "Östersund", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.01 },
  "Österåker": { kommunnamn: "Österåker", skattetabell: 29, defaultKolumn: 1, kommunalskatt: 29.22 },
  "Östhammar": { kommunnamn: "Östhammar", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 33.59 },
  "Östra Göinge": { kommunnamn: "Östra Göinge", skattetabell: 32, defaultKolumn: 1, kommunalskatt: 32.46 },
  "Överkalix": { kommunnamn: "Överkalix", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.43 },
  "Övertorneå": { kommunnamn: "Övertorneå", skattetabell: 34, defaultKolumn: 1, kommunalskatt: 34.13 },
};

export const KOMMUN_NAMES: string[] = Object.keys(KOMMUN_SKATT_2026).sort((a, b) =>
  a.localeCompare(b, "sv")
);

export function lookupKommunSkatt(name: string | null | undefined): KommunSkattInfo | null {
  if (!name) return null;
  if (KOMMUN_SKATT_2026[name]) return KOMMUN_SKATT_2026[name];
  const lower = name.toLowerCase();
  const key = Object.keys(KOMMUN_SKATT_2026).find(k => k.toLowerCase() === lower);
  return key ? KOMMUN_SKATT_2026[key] : null;
}

export const SKATTE_KOLUMN_DESCRIPTIONS: Record<string, string> = {
  "1": "Född 1961 eller senare, ej fyllt 66 år vid årets ingång",
  "2": "Fyllt 66 år vid årets ingång (lägre skatt)",
  "3": "Född 1938–1960, ej fyllt 66 år (förhöjt grundavdrag)",
  "4": "Sjöinkomst – närfart",
  "5": "Sjöinkomst – fjärrfart",
  "6": "Ej allmän pensionsavgift (begränsat skattskyldig)",
};
