import { useEffect, useRef } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useFirmDeadlineRadar } from "@/hooks/useFirmDeadlineRadar";
import { useAuth } from "@/hooks/useAuth";

/**
 * Auto-create firm_tasks from upcoming deadlines (VAT/AGI/INK2) so the
 * workflow board always reflects regulatory work without manual entry.
 *
 * Idempotent: a task is only inserted if one matching (firm_id, company_id,
 * task_type, due_date) does not already exist. Runs once per mount per firm.
 */
export function useAutoGenerateTasks(firmId: string | null) {
  const { items } = useFirmDeadlineRadar();
  const { user } = useAuth();
  const ranRef = useRef<string | null>(null);

  useEffect(() => {
    if (!firmId || !items.length || !user) return;
    if (ranRef.current === firmId) return;
    ranRef.current = firmId;

    (async () => {
      // Look up existing autogenerated tasks in scope
      const { data: existing } = await supabase
        .from("firm_tasks")
        .select("company_id, task_type, due_date")
        .eq("firm_id", firmId)
        .in(
          "task_type",
          items.map((i) => mapKindToTaskType(i.kind)),
        );

      const existingKey = new Set(
        (existing ?? []).map(
          (e) => `${e.company_id}|${e.task_type}|${e.due_date?.slice(0, 10) ?? ""}`,
        ),
      );

      const inserts = items
        .filter((i) => {
          const k = `${i.client_id}|${mapKindToTaskType(i.kind)}|${i.due_date.toISOString().slice(0, 10)}`;
          return !existingKey.has(k);
        })
        .map((i) => ({
          firm_id: firmId,
          company_id: i.client_id,
          title: `${i.label} – ${i.client_name}`,
          task_type: mapKindToTaskType(i.kind),
          priority:
            i.severity === "critical" ? "urgent" : i.severity === "warning" ? "high" : "medium",
          status: "todo" as const,
          due_date: i.due_date.toISOString().slice(0, 10),
          created_by: user.id,
        }));

      if (inserts.length === 0) return;

      // Use insert; ignore conflicts via best-effort try/catch
      await supabase.from("firm_tasks").insert(inserts);
    })();
  }, [firmId, items, user]);
}

function mapKindToTaskType(kind: string): string {
  switch (kind) {
    case "vat":
      return "vat";
    case "agi":
      return "agi";
    case "ink2":
      return "tax_return";
    case "annual":
      return "annual_report";
    default:
      return "other";
  }
}
