
-- BAS 2026 Kontoplan seed function
CREATE OR REPLACE FUNCTION public.seed_bas_2026_accounts(p_company_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_count integer := 0;
  v_accounts text[][] := ARRAY[
    -- Klass 1: Tillgångar
    ['1010','Utvecklingsutgifter','asset'],
    ['1020','Koncessioner','asset'],
    ['1030','Patent','asset'],
    ['1040','Licenser','asset'],
    ['1050','Goodwill','asset'],
    ['1060','Hyresrätter','asset'],
    ['1070','Övriga immateriella tillgångar','asset'],
    ['1080','Pågående projekt immateriella','asset'],
    ['1110','Byggnader','asset'],
    ['1120','Förbättringsutgifter annans fastighet','asset'],
    ['1130','Mark','asset'],
    ['1150','Markanläggningar','asset'],
    ['1180','Pågående nyanläggningar','asset'],
    ['1210','Maskiner och inventarier','asset'],
    ['1220','Inventarier och verktyg','asset'],
    ['1230','Installationer','asset'],
    ['1240','Bilar och transportmedel','asset'],
    ['1250','Datorer','asset'],
    ['1260','Leasade tillgångar','asset'],
    ['1290','Övriga materiella anläggningstillgångar','asset'],
    ['1310','Andelar i koncernföretag','asset'],
    ['1320','Långfristiga fordringar koncernföretag','asset'],
    ['1330','Andelar i intresseföretag','asset'],
    ['1340','Långfristiga fordringar intresseföretag','asset'],
    ['1350','Andelar i övriga företag','asset'],
    ['1360','Långfristiga fordringar övriga företag','asset'],
    ['1380','Andra långfristiga fordringar','asset'],
    ['1390','Ack avskrivning långfristiga fordringar','asset'],
    ['1410','Lager av råvaror','asset'],
    ['1420','Lager av tillsatsmaterial','asset'],
    ['1430','Lager av halvfabrikat','asset'],
    ['1440','Lager av produkter i arbete','asset'],
    ['1450','Lager av färdiga varor','asset'],
    ['1460','Lager av handelsvaror','asset'],
    ['1470','Pågående arbeten','asset'],
    ['1480','Förskott till leverantörer','asset'],
    ['1490','Övriga lagertillgångar','asset'],
    ['1510','Kundfordringar','asset'],
    ['1511','Kundfordringar ej fakturerade','asset'],
    ['1512','Osäkra kundfordringar','asset'],
    ['1519','Värdereglering kundfordringar','asset'],
    ['1580','Fordringar hos koncernföretag','asset'],
    ['1610','Fordringar hos anställda','asset'],
    ['1620','Upparbetad men ej fakturerad intäkt','asset'],
    ['1630','Avräkning för skatter och avgifter','asset'],
    ['1640','Skattefordringar','asset'],
    ['1650','Momsfordran','asset'],
    ['1660','Fordringar hos intresseföretag','asset'],
    ['1680','Övriga kortfristiga fordringar','asset'],
    ['1690','Värdereglering kortfristiga fordringar','asset'],
    ['1710','Förutbetalda hyror','asset'],
    ['1720','Förutbetalda leasingavgifter','asset'],
    ['1730','Förutbetalda försäkringspremier','asset'],
    ['1740','Förutbetalda räntekostnader','asset'],
    ['1750','Upplupna hyresintäkter','asset'],
    ['1760','Upplupna ränteintäkter','asset'],
    ['1790','Övriga förutbetalda kostnader och upplupna intäkter','asset'],
    ['1810','Andelar i börsnoterade företag','asset'],
    ['1820','Obligationer','asset'],
    ['1830','Andelar i bostadsrättsföreningar','asset'],
    ['1880','Övriga kortfristiga placeringar','asset'],
    ['1910','Kassa','asset'],
    ['1920','PlusGiro','asset'],
    ['1930','Företagskonto/checkkonto','asset'],
    ['1940','Övriga bankkonton','asset'],
    ['1950','Bankcertifikat','asset'],
    ['1960','Koncernkonto moderföretag','asset'],
    ['1970','Särskilda bankkonton','asset'],
    ['1980','Övriga likvida medel','asset'],

    -- Klass 2: Skulder och eget kapital
    ['2010','Eget kapital','equity'],
    ['2011','Eget kapital, individuella företag','equity'],
    ['2013','Övriga egna insättningar','equity'],
    ['2018','Egna uttag','equity'],
    ['2019','Årets resultat','equity'],
    ['2020','Eget kapital i ideella föreningar','equity'],
    ['2081','Aktiekapital','equity'],
    ['2082','Ej registrerat aktiekapital','equity'],
    ['2083','Erhållna aktieägartillskott','equity'],
    ['2084','Överkursfond','equity'],
    ['2085','Uppskrivningsfond','equity'],
    ['2086','Reservfond','equity'],
    ['2087','Fond för verkligt värde','equity'],
    ['2089','Fond för utvecklingsutgifter','equity'],
    ['2091','Balanserat resultat','equity'],
    ['2097','Överkursfond','equity'],
    ['2098','Vinst eller förlust från föregående år','equity'],
    ['2099','Årets resultat','equity'],
    ['2110','Obeskattade reserver','liability'],
    ['2120','Periodiseringsfonder','liability'],
    ['2130','Överavskrivningar','liability'],
    ['2150','Ackumulerade överavskrivningar','liability'],
    ['2210','Avsättningar för pensioner','liability'],
    ['2220','Avsättningar för skatter','liability'],
    ['2230','Övriga avsättningar','liability'],
    ['2240','Avsättningar för garantier','liability'],
    ['2250','Övriga avsättningar för pensioner','liability'],
    ['2310','Banklån','liability'],
    ['2320','Checkräkningskredit','liability'],
    ['2330','Övriga skulder till kreditinstitut','liability'],
    ['2340','Byggnadskreditiv','liability'],
    ['2350','Skulder till koncernföretag','liability'],
    ['2360','Skulder till intresseföretag','liability'],
    ['2390','Övriga långfristiga skulder','liability'],
    ['2410','Leverantörsskulder','liability'],
    ['2420','Förskott från kunder','liability'],
    ['2430','Pågående arbeten','liability'],
    ['2440','Leverantörsskulder','liability'],
    ['2510','Skatteskulder','liability'],
    ['2610','Utgående moms 25%','liability'],
    ['2620','Utgående moms 12%','liability'],
    ['2630','Utgående moms 6%','liability'],
    ['2640','Ingående moms','liability'],
    ['2641','Debiterad ingående moms','liability'],
    ['2645','Beräknad ingående moms','liability'],
    ['2650','Redovisningskonto för moms','liability'],
    ['2660','Särskild moms','liability'],
    ['2710','Personalskatt','liability'],
    ['2730','Skuld till anställda - nettolön','liability'],
    ['2731','Semesterskuld','liability'],
    ['2732','Löneskuld','liability'],
    ['2740','Upplupen arbetsgivaravgift','liability'],
    ['2750','Upplupen avtalad pension','liability'],
    ['2760','Upplupen särskild löneskatt pension','liability'],
    ['2790','Övriga upplupna kostnader och förutbetalda intäkter','liability'],
    ['2810','Avräkning för skatter och avgifter','liability'],
    ['2820','Kortfristiga skulder koncernföretag','liability'],
    ['2840','Kortfristiga skulder intresseföretag','liability'],
    ['2860','Kortfristiga skulder övriga','liability'],
    ['2890','Övriga kortfristiga skulder','liability'],
    ['2910','Upplupna löner','liability'],
    ['2920','Upplupna semesterlöner','liability'],
    ['2940','Upplupna lagstadgade sociala avgifter','liability'],
    ['2941','Upplupna arbetsgivaravgifter','liability'],
    ['2950','Upplupna avtalade sociala avgifter','liability'],
    ['2960','Upplupna räntekostnader','liability'],
    ['2970','Förutbetalda intäkter','liability'],
    ['2980','Upplupna kostnader','liability'],
    ['2990','Övriga upplupna kostnader','liability'],

    -- Klass 3: Intäkter
    ['3010','Försäljning varor 25% moms','income'],
    ['3011','Försäljning varor 12% moms','income'],
    ['3012','Försäljning varor 6% moms','income'],
    ['3013','Försäljning varor momsfri','income'],
    ['3040','Försäljning tjänster 25% moms','income'],
    ['3041','Försäljning tjänster 12% moms','income'],
    ['3042','Försäljning tjänster 6% moms','income'],
    ['3043','Försäljning tjänster momsfri','income'],
    ['3050','Försäljning konsulttjänster','income'],
    ['3060','Försäljning abonnemang/licenser','income'],
    ['3100','Försäljning, gruppkonto','income'],
    ['3200','Försäljning inom Sverige','income'],
    ['3300','Försäljning varor EU','income'],
    ['3305','Försäljning tjänster EU','income'],
    ['3310','Försäljning varor utanför EU','income'],
    ['3400','Försäljning, ej moms','income'],
    ['3500','Fakturerade kostnader','income'],
    ['3510','Fakturerat emballage','income'],
    ['3520','Fakturerade frakter','income'],
    ['3540','Fakturerade tull- och speditionskostnader','income'],
    ['3590','Övriga fakturerade kostnader','income'],
    ['3600','Sidointäkter','income'],
    ['3610','Försäljning material och skrot','income'],
    ['3620','Tillfällig uthyrning','income'],
    ['3690','Övriga sidointäkter','income'],
    ['3700','Intäktskorrigeringar','income'],
    ['3710','Kassarabatter','income'],
    ['3730','Lämnade rabatter','income'],
    ['3740','Öres- och kronavrundning','income'],
    ['3750','Erhållna bonus','income'],
    ['3790','Övriga intäktskorrigeringar','income'],
    ['3800','Aktiverat arbete för egen räkning','income'],
    ['3900','Övriga rörelseintäkter','income'],
    ['3910','Hyresintäkter','income'],
    ['3920','Provisionsintäkter','income'],
    ['3960','Valutakursvinster','income'],
    ['3970','Vinst vid avyttring materiella anläggningstillgångar','income'],
    ['3980','Erhållna offentliga stöd/bidrag','income'],
    ['3990','Övriga ersättningar och intäkter','income'],

    -- Klass 4: Kostnader för varor och material
    ['4010','Inköp varor och material','expense'],
    ['4012','Inköp varor 12%','expense'],
    ['4013','Inköp varor momsfri','expense'],
    ['4040','Inköp varor inom EU','expense'],
    ['4050','Inköp varor utanför EU','expense'],
    ['4100','Inköp råvaror och förnödenheter','expense'],
    ['4200','Inköp halvfabrikat','expense'],
    ['4300','Inköp handelsvaror','expense'],
    ['4400','Inköp underleverantörer','expense'],
    ['4500','Övriga inköp','expense'],
    ['4510','Import','expense'],
    ['4531','Tull','expense'],
    ['4532','Spedition','expense'],
    ['4535','Frakter','expense'],
    ['4600','Legoarbeten','expense'],
    ['4700','Förändring av lager','expense'],
    ['4900','Övriga kostnader för sålda varor','expense'],
    ['4910','Förändring pågående arbeten','expense'],
    ['4920','Lagerförändringar','expense'],
    ['4960','Valutakursförluster varuinköp','expense'],
    ['4970','Inkurans','expense'],
    ['4990','Övriga lagerjusteringar','expense'],

    -- Klass 5: Lokalkostnader
    ['5010','Lokalhyra','expense'],
    ['5020','El för lokaler','expense'],
    ['5030','Värme','expense'],
    ['5040','Vatten och avlopp','expense'],
    ['5050','Lokaltillbehör','expense'],
    ['5060','Städning och renhållning','expense'],
    ['5070','Reparation och underhåll av lokaler','expense'],
    ['5090','Övriga lokalkostnader','expense'],
    ['5100','Fastighetskostnader','expense'],
    ['5110','Tomträttsavgäld/arrende','expense'],
    ['5120','Reparation och underhåll fastighet','expense'],
    ['5130','Fastighetsskatt','expense'],
    ['5170','Fastighetsskötsel och förvaltning','expense'],
    ['5190','Övriga fastighetskostnader','expense'],
    ['5200','Hyra av anläggningstillgångar','expense'],
    ['5210','Hyra/leasing av maskiner','expense'],
    ['5220','Hyra/leasing av inventarier','expense'],
    ['5250','Hyra/leasing av datorer','expense'],
    ['5260','Hyra/leasing av bilar','expense'],
    ['5290','Övriga hyreskostnader','expense'],

    -- Klass 6: Övriga externa kostnader
    ['6010','Kontorsmateriel','expense'],
    ['6040','Förbrukningsinventarier','expense'],
    ['6050','Förbrukningsmaterial','expense'],
    ['6060','Sjukvård och läkemedel','expense'],
    ['6070','Representation','expense'],
    ['6071','Representation avdragsgill','expense'],
    ['6072','Representation ej avdragsgill','expense'],
    ['6090','Övriga förbrukningskostnader','expense'],
    ['6100','Kontorsmaterial och trycksaker','expense'],
    ['6110','Kontorsmaterial','expense'],
    ['6150','Trycksaker','expense'],
    ['6200','Tele och post','expense'],
    ['6210','Telekommunikation','expense'],
    ['6211','Telefon','expense'],
    ['6212','Mobiltelefon','expense'],
    ['6214','Bredband/internet','expense'],
    ['6230','Datakommunikation','expense'],
    ['6250','Postbefordran','expense'],
    ['6300','Företagsförsäkringar och riskkostnader','expense'],
    ['6310','Företagsförsäkringar','expense'],
    ['6320','Ansvarsförsäkring','expense'],
    ['6340','Lagerförsäkring','expense'],
    ['6350','Fordonsförsäkring','expense'],
    ['6360','Maskinförsäkring','expense'],
    ['6370','Förluster kundfordringar','expense'],
    ['6380','Förluster övriga kortfristiga fordringar','expense'],
    ['6390','Övriga riskkostnader','expense'],
    ['6400','Förvaltningskostnader','expense'],
    ['6410','Styrelsearvoden','expense'],
    ['6420','Revisionsarvoden','expense'],
    ['6430','Management fee','expense'],
    ['6440','Juridiska konsultarvoden','expense'],
    ['6450','Konsultarvoden, övriga','expense'],
    ['6460','Redovisningstjänster','expense'],
    ['6490','Övriga förvaltningskostnader','expense'],
    ['6500','Övriga externa tjänster','expense'],
    ['6510','IT-tjänster','expense'],
    ['6520','Rekryteringstjänster','expense'],
    ['6530','Företagshälsovård','expense'],
    ['6540','Bevakningstjänster','expense'],
    ['6550','Konsulttjänster','expense'],
    ['6560','Serviceavgifter','expense'],
    ['6570','Bankkostnader','expense'],
    ['6580','Advokat- och rättegångskostnader','expense'],
    ['6590','Övriga externa tjänster','expense'],
    ['6800','Inhyrd personal','expense'],
    ['6900','Övriga externa kostnader','expense'],
    ['6910','Licensavgifter','expense'],
    ['6920','Patentavgifter','expense'],
    ['6970','Tidningar, facklitteratur','expense'],
    ['6980','Föreningsavgifter','expense'],
    ['6990','Övriga externa kostnader','expense'],

    -- Klass 7: Personal och avskrivningar
    ['7010','Löner tjänstemän','expense'],
    ['7011','Löner, kollektivanställda','expense'],
    ['7012','Timlöner','expense'],
    ['7018','Sjuklön','expense'],
    ['7019','Övriga löner','expense'],
    ['7030','Tantiem och bonus','expense'],
    ['7082','Semesterlön','expense'],
    ['7090','Förändring av semesterskuld','expense'],
    ['7200','Löner VD och styrelse','expense'],
    ['7210','Löner VD','expense'],
    ['7220','Styrelsearvoden','expense'],
    ['7290','Övriga löner till VD/styrelse','expense'],
    ['7310','Kontanta extraersättningar','expense'],
    ['7320','Traktamenten skattefria','expense'],
    ['7321','Traktamenten skattepliktiga','expense'],
    ['7322','Bilersättningar skattefria','expense'],
    ['7323','Bilersättningar skattepliktiga','expense'],
    ['7330','Bilförmån','expense'],
    ['7332','Kostförmån','expense'],
    ['7333','Bostadsförmån','expense'],
    ['7340','Lunchkuponger','expense'],
    ['7350','Sjuk- och hälsovård','expense'],
    ['7380','Kostnader för förmåner','expense'],
    ['7381','Personalrepresentation','expense'],
    ['7382','Utbildning','expense'],
    ['7385','Personalfester','expense'],
    ['7390','Övriga personalkostnader','expense'],
    ['7400','Pensionskostnader','expense'],
    ['7410','Pensionsförsäkringspremier','expense'],
    ['7411','Premiepension','expense'],
    ['7412','ITP-premier','expense'],
    ['7420','Pensionsstiftelse','expense'],
    ['7430','Avdragsgilla pensionskostnader','expense'],
    ['7490','Övriga pensionskostnader','expense'],
    ['7510','Arbetsgivaravgifter','expense'],
    ['7511','Sociala avgifter löner','expense'],
    ['7512','Sociala avgifter semester','expense'],
    ['7530','Särskild löneskatt','expense'],
    ['7533','Särskild löneskatt pensionskostnader','expense'],
    ['7550','Avtalade sociala avgifter','expense'],
    ['7570','Premier för arbetsmarknadsförsäkringar','expense'],
    ['7580','Grupplivförsäkring','expense'],
    ['7610','Utbildning','expense'],
    ['7620','Sjuk- och hälsovård','expense'],
    ['7631','Personalrepresentation avdragsgill','expense'],
    ['7632','Personalrepresentation ej avdragsgill','expense'],
    ['7690','Övriga personalkostnader','expense'],
    ['7710','Nedskrivningar immateriella tillgångar','expense'],
    ['7720','Nedskrivningar byggnader och mark','expense'],
    ['7730','Nedskrivningar maskiner och inventarier','expense'],
    ['7810','Avskrivningar immateriella tillgångar','expense'],
    ['7820','Avskrivningar byggnader','expense'],
    ['7830','Avskrivningar maskiner och inventarier','expense'],
    ['7832','Avskrivningar inventarier','expense'],
    ['7834','Avskrivningar bilar','expense'],
    ['7835','Avskrivningar datorer','expense'],
    ['7840','Avskrivningar förbättringsutgifter','expense'],

    -- Klass 8: Finansiella poster och skatt
    ['8010','Ränteintäkter koncernföretag','income'],
    ['8020','Ränteintäkter intresseföretag','income'],
    ['8110','Utdelning på andelar koncernföretag','income'],
    ['8120','Utdelning på andelar intresseföretag','income'],
    ['8210','Ränteintäkter bank','income'],
    ['8220','Ränteintäkter kundfordringar','income'],
    ['8230','Ränteintäkter skattemyndigheten','income'],
    ['8290','Övriga finansiella intäkter','income'],
    ['8300','Ränteintäkter, övriga','income'],
    ['8310','Ränteintäkter','income'],
    ['8330','Valutakursvinster finansiella poster','income'],
    ['8340','Utdelningar','income'],
    ['8350','Resultat vid försäljning av värdepapper','income'],
    ['8390','Övriga finansiella intäkter','income'],
    ['8410','Räntekostnader koncernföretag','expense'],
    ['8420','Räntekostnader intresseföretag','expense'],
    ['8510','Räntekostnader bank','expense'],
    ['8520','Räntekostnader leverantörsskulder','expense'],
    ['8530','Räntekostnader skattemyndigheten','expense'],
    ['8540','Räntekostnader övriga skulder','expense'],
    ['8570','Bankavgifter','expense'],
    ['8580','Dröjsmålsräntor','expense'],
    ['8590','Övriga finansiella kostnader','expense'],
    ['8610','Valutakursförluster finansiella poster','expense'],
    ['8710','Extraordinära intäkter','income'],
    ['8750','Erhållna koncernbidrag','income'],
    ['8760','Lämnade koncernbidrag','expense'],
    ['8810','Förändring periodiseringsfond','expense'],
    ['8820','Förändring överavskrivningar','expense'],
    ['8830','Förändring övriga obeskattade reserver','expense'],
    ['8910','Skatt på årets resultat','expense'],
    ['8920','Uppskjuten skatt','expense'],
    ['8990','Resultat','expense'],
    ['8999','Årets resultat','equity']
  ];
  v_rec text[];
BEGIN
  FOREACH v_rec SLICE 1 IN ARRAY v_accounts LOOP
    INSERT INTO public.chart_of_accounts (company_id, account_number, account_name, account_type, is_active)
    VALUES (p_company_id, v_rec[1], v_rec[2], v_rec[3], true)
    ON CONFLICT DO NOTHING;
    v_count := v_count + 1;
  END LOOP;
  
  RETURN v_count;
END;
$$;

-- Update the trigger to seed BAS 2026 accounts for new companies
CREATE OR REPLACE FUNCTION public.create_default_company_for_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_company_id UUID;
  v_unique_org TEXT;
BEGIN
  v_unique_org := 'TEMP-' || substring(NEW.id::text from 1 for 8);

  INSERT INTO public.companies (
    name,
    org_number,
    created_by,
    created_at,
    updated_at
  ) VALUES (
    'Mitt Företag',
    v_unique_org,
    NEW.id,
    now(),
    now()
  ) RETURNING id INTO v_company_id;

  -- Seed BAS 2026 accounts for the new company
  PERFORM public.seed_bas_2026_accounts(v_company_id);

  RETURN NEW;
END;
$$;
