ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS fiscal_year_start DATE DEFAULT '2025-01-01',
  ADD COLUMN IF NOT EXISTS fiscal_year_end DATE DEFAULT '2025-12-31',
  ADD COLUMN IF NOT EXISTS company_type TEXT DEFAULT 'AB',
  ADD COLUMN IF NOT EXISTS registered_for_fskatt BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS num_employees INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eu_vat_liable BOOLEAN DEFAULT FALSE;