
-- Expand BAS 2026 seed function with comprehensive accounts + VAT codes
-- Adds ~170 new accounts (bringing total to ~450) and sets VAT codes on all relevant accounts

CREATE OR REPLACE FUNCTION public.seed_bas_2026_accounts(p_company_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_count integer := 0;
  v_accounts text[][] := ARRAY[
    -- ========== Klass 1: Tillgångar ==========
    -- 10xx Immateriella anläggningstillgångar
    ['1010','Utvecklingsutgifter','asset',NULL],
    ['1012','Balanserade utgifter för FoU','asset',NULL],
    ['1019','Ack avskrivning utvecklingsutgifter','asset',NULL],
    ['1020','Koncessioner','asset',NULL],
    ['1029','Ack avskrivning koncessioner','asset',NULL],
    ['1030','Patent','asset',NULL],
    ['1039','Ack avskrivning patent','asset',NULL],
    ['1040','Licenser','asset',NULL],
    ['1049','Ack avskrivning licenser','asset',NULL],
    ['1050','Goodwill','asset',NULL],
    ['1059','Ack avskrivning goodwill','asset',NULL],
    ['1060','Hyresrätter','asset',NULL],
    ['1069','Ack avskrivning hyresrätter','asset',NULL],
    ['1070','Övriga immateriella tillgångar','asset',NULL],
    ['1079','Ack avskrivning övriga immateriella','asset',NULL],
    ['1080','Pågående projekt immateriella','asset',NULL],
    -- 11xx Byggnader och mark
    ['1110','Byggnader','asset',NULL],
    ['1119','Ack avskrivning byggnader','asset',NULL],
    ['1120','Förbättringsutgifter annans fastighet','asset',NULL],
    ['1129','Ack avskrivning förbättringsutgifter','asset',NULL],
    ['1130','Mark','asset',NULL],
    ['1150','Markanläggningar','asset',NULL],
    ['1159','Ack avskrivning markanläggningar','asset',NULL],
    ['1180','Pågående nyanläggningar fastigheter','asset',NULL],
    -- 12xx Maskiner och inventarier
    ['1210','Maskiner och inventarier','asset',NULL],
    ['1219','Ack avskrivning maskiner','asset',NULL],
    ['1220','Inventarier och verktyg','asset',NULL],
    ['1229','Ack avskrivning inventarier','asset',NULL],
    ['1230','Installationer','asset',NULL],
    ['1239','Ack avskrivning installationer','asset',NULL],
    ['1240','Bilar och transportmedel','asset',NULL],
    ['1249','Ack avskrivning bilar','asset',NULL],
    ['1250','Datorer','asset',NULL],
    ['1257','Programvaror','asset',NULL],
    ['1259','Ack avskrivning datorer','asset',NULL],
    ['1260','Leasade tillgångar','asset',NULL],
    ['1269','Ack avskrivning leasade tillgångar','asset',NULL],
    ['1280','Pågående nyanläggningar materiella','asset',NULL],
    ['1290','Övriga materiella anläggningstillgångar','asset',NULL],
    ['1299','Ack avskrivning övriga materiella','asset',NULL],
    -- 13xx Finansiella anläggningstillgångar
    ['1310','Andelar i koncernföretag','asset',NULL],
    ['1320','Långfristiga fordringar koncernföretag','asset',NULL],
    ['1330','Andelar i intresseföretag','asset',NULL],
    ['1340','Långfristiga fordringar intresseföretag','asset',NULL],
    ['1350','Andelar i övriga företag','asset',NULL],
    ['1360','Långfristiga fordringar övriga företag','asset',NULL],
    ['1380','Andra långfristiga fordringar','asset',NULL],
    ['1381','Långfristiga reversfordringar','asset',NULL],
    ['1382','Depositioner','asset',NULL],
    ['1390','Ack avskrivning långfristiga fordringar','asset',NULL],
    -- 14xx Lager
    ['1410','Lager av råvaror','asset',NULL],
    ['1420','Lager av tillsatsmaterial','asset',NULL],
    ['1430','Lager av halvfabrikat','asset',NULL],
    ['1440','Lager av produkter i arbete','asset',NULL],
    ['1450','Lager av färdiga varor','asset',NULL],
    ['1460','Lager av handelsvaror','asset',NULL],
    ['1470','Pågående arbeten','asset',NULL],
    ['1480','Förskott till leverantörer','asset',NULL],
    ['1490','Övriga lagertillgångar','asset',NULL],
    -- 15xx Kundfordringar
    ['1510','Kundfordringar','asset',NULL],
    ['1511','Kundfordringar ej fakturerade','asset',NULL],
    ['1512','Osäkra kundfordringar','asset',NULL],
    ['1513','Kundfordringar - Loss','asset',NULL],
    ['1519','Värdereglering kundfordringar','asset',NULL],
    ['1520','Växelfordringar','asset',NULL],
    ['1530','Kontraktsfordringar','asset',NULL],
    ['1560','Kundfordringar koncernföretag','asset',NULL],
    ['1570','Kundfordringar intresseföretag','asset',NULL],
    ['1580','Fordringar hos koncernföretag','asset',NULL],
    -- 16xx Övriga kortfristiga fordringar
    ['1610','Fordringar hos anställda','asset',NULL],
    ['1611','Reseförskott','asset',NULL],
    ['1612','Kassaförskott','asset',NULL],
    ['1613','Lån till anställda','asset',NULL],
    ['1620','Upparbetad men ej fakturerad intäkt','asset',NULL],
    ['1630','Avräkning för skatter och avgifter','asset',NULL],
    ['1640','Skattefordringar','asset',NULL],
    ['1650','Momsfordran','asset',NULL],
    ['1660','Fordringar hos intresseföretag','asset',NULL],
    ['1670','Fordringar hos övriga företag','asset',NULL],
    ['1680','Övriga kortfristiga fordringar','asset',NULL],
    ['1681','Utlägg för kunder','asset',NULL],
    ['1682','Fordringar för tecknat men ej inbetalt kapital','asset',NULL],
    ['1690','Värdereglering kortfristiga fordringar','asset',NULL],
    -- 17xx Förutbetalda kostnader
    ['1710','Förutbetalda hyror','asset',NULL],
    ['1720','Förutbetalda leasingavgifter','asset',NULL],
    ['1730','Förutbetalda försäkringspremier','asset',NULL],
    ['1740','Förutbetalda räntekostnader','asset',NULL],
    ['1750','Upplupna hyresintäkter','asset',NULL],
    ['1760','Upplupna ränteintäkter','asset',NULL],
    ['1790','Övriga förutbetalda kostnader och upplupna intäkter','asset',NULL],
    -- 18xx Kortfristiga placeringar
    ['1810','Andelar i börsnoterade företag','asset',NULL],
    ['1820','Obligationer','asset',NULL],
    ['1830','Andelar i bostadsrättsföreningar','asset',NULL],
    ['1880','Övriga kortfristiga placeringar','asset',NULL],
    -- 19xx Kassa och bank
    ['1910','Kassa','asset',NULL],
    ['1920','PlusGiro','asset',NULL],
    ['1930','Företagskonto/checkkonto','asset',NULL],
    ['1940','Övriga bankkonton','asset',NULL],
    ['1941','Bankkonto SEK','asset',NULL],
    ['1942','Bankkonto EUR','asset',NULL],
    ['1943','Bankkonto USD','asset',NULL],
    ['1945','Bankkonto sparkonto','asset',NULL],
    ['1950','Bankcertifikat','asset',NULL],
    ['1960','Koncernkonto moderföretag','asset',NULL],
    ['1970','Särskilda bankkonton','asset',NULL],
    ['1980','Övriga likvida medel','asset',NULL],
    ['1990','Redovisningsmedel','asset',NULL],

    -- ========== Klass 2: Skulder och eget kapital ==========
    ['2010','Eget kapital','equity',NULL],
    ['2011','Eget kapital, individuella företag','equity',NULL],
    ['2013','Övriga egna insättningar','equity',NULL],
    ['2017','Förändringar i fond för verkligt värde','equity',NULL],
    ['2018','Egna uttag','equity',NULL],
    ['2019','Årets resultat individuellt','equity',NULL],
    ['2020','Eget kapital i ideella föreningar','equity',NULL],
    ['2030','Eget kapital i handelsbolag','equity',NULL],
    ['2040','Eget kapital i kommanditbolag','equity',NULL],
    ['2050','Insatskapital i ekonomisk förening','equity',NULL],
    ['2060','Eget kapital i stiftelser','equity',NULL],
    ['2081','Aktiekapital','equity',NULL],
    ['2082','Ej registrerat aktiekapital','equity',NULL],
    ['2083','Erhållna aktieägartillskott','equity',NULL],
    ['2084','Överkursfond','equity',NULL],
    ['2085','Uppskrivningsfond','equity',NULL],
    ['2086','Reservfond','equity',NULL],
    ['2087','Fond för verkligt värde','equity',NULL],
    ['2088','Fond för utvecklingsutgifter','equity',NULL],
    ['2089','Fond för utvecklingsutgifter','equity',NULL],
    ['2091','Balanserat resultat','equity',NULL],
    ['2092','Mottagna aktieägartillskott','equity',NULL],
    ['2093','Erhållet villkorat aktieägartillskott','equity',NULL],
    ['2094','Lämnat villkorat aktieägartillskott','equity',NULL],
    ['2095','Fusionsresultat','equity',NULL],
    ['2096','Fond för yttre underhåll','equity',NULL],
    ['2097','Överkursfond, reserv','equity',NULL],
    ['2098','Vinst eller förlust från föregående år','equity',NULL],
    ['2099','Årets resultat','equity',NULL],
    -- 21xx Obeskattade reserver
    ['2110','Obeskattade reserver','liability',NULL],
    ['2120','Periodiseringsfonder','liability',NULL],
    ['2123','Periodiseringsfond tax 2023','liability',NULL],
    ['2124','Periodiseringsfond tax 2024','liability',NULL],
    ['2125','Periodiseringsfond tax 2025','liability',NULL],
    ['2126','Periodiseringsfond tax 2026','liability',NULL],
    ['2130','Överavskrivningar','liability',NULL],
    ['2150','Ackumulerade överavskrivningar','liability',NULL],
    -- 22xx Avsättningar
    ['2210','Avsättningar för pensioner','liability',NULL],
    ['2220','Avsättningar för skatter','liability',NULL],
    ['2230','Övriga avsättningar','liability',NULL],
    ['2240','Avsättningar för garantier','liability',NULL],
    ['2250','Övriga avsättningar för pensioner','liability',NULL],
    -- 23xx Långfristiga skulder
    ['2310','Banklån','liability',NULL],
    ['2320','Checkräkningskredit','liability',NULL],
    ['2321','Utnyttjad checkräkningskredit','liability',NULL],
    ['2322','Beviljad checkräkningskredit','liability',NULL],
    ['2330','Övriga skulder till kreditinstitut','liability',NULL],
    ['2340','Byggnadskreditiv','liability',NULL],
    ['2350','Skulder till koncernföretag','liability',NULL],
    ['2355','Skulder till koncernföretag, lång','liability',NULL],
    ['2360','Skulder till intresseföretag','liability',NULL],
    ['2370','Skulder till delägare/närstående','liability',NULL],
    ['2390','Övriga långfristiga skulder','liability',NULL],
    ['2393','Lån från närstående, lång','liability',NULL],
    ['2395','Villkorade aktieägartillskott','liability',NULL],
    -- 24xx Leverantörsskulder
    ['2410','Leverantörsskulder','liability',NULL],
    ['2420','Förskott från kunder','liability',NULL],
    ['2430','Pågående arbeten skuld','liability',NULL],
    ['2440','Leverantörsskulder koncernföretag','liability',NULL],
    ['2450','Leverantörsskulder intresseföretag','liability',NULL],
    ['2460','Leverantörsskulder övriga','liability',NULL],
    -- 25xx Skatteskulder
    ['2510','Skatteskulder','liability',NULL],
    ['2512','Beräknad inkomstskatt','liability',NULL],
    ['2513','Kvarskatt','liability',NULL],
    ['2514','Beräknad fastighetsskatt','liability',NULL],
    ['2515','Beräknad särskild löneskatt','liability',NULL],
    ['2518','Betald F-skatt','liability',NULL],
    -- 26xx Moms
    ['2610','Utgående moms 25%','liability',NULL],
    ['2611','Utgående moms på varor 25%','liability',NULL],
    ['2612','Utgående moms på tjänster 25%','liability',NULL],
    ['2614','Utgående moms omvänd skattskyldighet 25%','liability',NULL],
    ['2615','Utgående moms import 25%','liability',NULL],
    ['2620','Utgående moms 12%','liability',NULL],
    ['2621','Utgående moms på varor 12%','liability',NULL],
    ['2622','Utgående moms på tjänster 12%','liability',NULL],
    ['2630','Utgående moms 6%','liability',NULL],
    ['2631','Utgående moms på varor 6%','liability',NULL],
    ['2632','Utgående moms på tjänster 6%','liability',NULL],
    ['2640','Ingående moms','liability',NULL],
    ['2641','Debiterad ingående moms','liability',NULL],
    ['2642','Ingående moms omvänd skattskyldighet','liability',NULL],
    ['2645','Beräknad ingående moms','liability',NULL],
    ['2646','Ingående moms import','liability',NULL],
    ['2650','Redovisningskonto för moms','liability',NULL],
    ['2660','Särskild moms','liability',NULL],
    -- 27xx Personalens skulder
    ['2710','Personalskatt','liability',NULL],
    ['2730','Skuld till anställda - nettolön','liability',NULL],
    ['2731','Semesterskuld','liability',NULL],
    ['2732','Löneskuld','liability',NULL],
    ['2740','Upplupen arbetsgivaravgift','liability',NULL],
    ['2750','Upplupen avtalad pension','liability',NULL],
    ['2760','Upplupen särskild löneskatt pension','liability',NULL],
    ['2790','Övriga upplupna kostnader personalens skatter','liability',NULL],
    -- 28xx Övriga kortfristiga skulder
    ['2810','Avräkning för skatter och avgifter','liability',NULL],
    ['2820','Kortfristiga skulder koncernföretag','liability',NULL],
    ['2840','Kortfristiga skulder intresseföretag','liability',NULL],
    ['2850','Avräkning för utlägg/fordringar','liability',NULL],
    ['2860','Kortfristiga skulder övriga','liability',NULL],
    ['2890','Övriga kortfristiga skulder','liability',NULL],
    -- 29xx Upplupna kostnader
    ['2910','Upplupna löner','liability',NULL],
    ['2920','Upplupna semesterlöner','liability',NULL],
    ['2930','Upplupna pensionskostnader','liability',NULL],
    ['2940','Upplupna lagstadgade sociala avgifter','liability',NULL],
    ['2941','Upplupna arbetsgivaravgifter','liability',NULL],
    ['2950','Upplupna avtalade sociala avgifter','liability',NULL],
    ['2960','Upplupna räntekostnader','liability',NULL],
    ['2970','Förutbetalda intäkter','liability',NULL],
    ['2971','Förutbetalda hyresintäkter','liability',NULL],
    ['2972','Förutbetalda abonnemangsintäkter','liability',NULL],
    ['2979','Övriga förutbetalda intäkter','liability',NULL],
    ['2980','Upplupna kostnader','liability',NULL],
    ['2990','Övriga upplupna kostnader','liability',NULL],

    -- ========== Klass 3: Intäkter ==========
    ['3010','Försäljning varor 25% moms','income','25'],
    ['3011','Försäljning varor 12% moms','income','12'],
    ['3012','Försäljning varor 6% moms','income','6'],
    ['3013','Försäljning varor momsfri','income','0'],
    ['3014','Försäljning varor, ej moms','income','0'],
    ['3040','Försäljning tjänster 25% moms','income','25'],
    ['3041','Försäljning tjänster 12% moms','income','12'],
    ['3042','Försäljning tjänster 6% moms','income','6'],
    ['3043','Försäljning tjänster momsfri','income','0'],
    ['3044','Försäljning tjänster, ej moms','income','0'],
    ['3050','Försäljning konsulttjänster','income','25'],
    ['3051','Försäljning konsulttjänster EU','income','0'],
    ['3052','Försäljning konsulttjänster utanför EU','income','0'],
    ['3060','Försäljning abonnemang/licenser','income','25'],
    ['3061','Försäljning SaaS/licenser','income','25'],
    ['3070','Försäljning returemballage','income','25'],
    ['3080','Försäljning provision','income','25'],
    ['3100','Försäljning, gruppkonto','income','25'],
    ['3200','Försäljning inom Sverige','income','25'],
    ['3211','Försäljning inom Sverige, varor','income','25'],
    ['3231','Försäljning inom Sverige, tjänster','income','25'],
    ['3300','Försäljning varor EU','income','0'],
    ['3305','Försäljning tjänster EU','income','0'],
    ['3308','Försäljning, trepartshandel','income','0'],
    ['3310','Försäljning varor utanför EU','income','0'],
    ['3311','Försäljning tjänster utanför EU','income','0'],
    ['3400','Försäljning, ej moms','income','0'],
    ['3401','Försäljning omsättning beskattningsland','income','0'],
    ['3404','Försäljning finansiella tjänster','income','0'],
    ['3500','Fakturerade kostnader','income','25'],
    ['3510','Fakturerat emballage','income','25'],
    ['3520','Fakturerade frakter','income','25'],
    ['3530','Fakturerade tull- och speditionskostnader','income','25'],
    ['3540','Fakturerade tull- och speditionskostnader, övrigt','income','25'],
    ['3550','Fakturerade resekostnader','income','25'],
    ['3590','Övriga fakturerade kostnader','income','25'],
    ['3600','Sidointäkter','income','25'],
    ['3610','Försäljning material och skrot','income','25'],
    ['3611','Försäljning av förbrukningsinventarier','income','25'],
    ['3620','Tillfällig uthyrning','income','25'],
    ['3690','Övriga sidointäkter','income','25'],
    ['3700','Intäktskorrigeringar','income',NULL],
    ['3710','Kassarabatter','income',NULL],
    ['3730','Lämnade rabatter','income',NULL],
    ['3731','Lämnade kundrabatter','income',NULL],
    ['3740','Öres- och kronavrundning','income',NULL],
    ['3750','Erhållna bonus','income',NULL],
    ['3790','Övriga intäktskorrigeringar','income',NULL],
    ['3800','Aktiverat arbete för egen räkning','income',NULL],
    ['3900','Övriga rörelseintäkter','income','25'],
    ['3910','Hyresintäkter','income','25'],
    ['3911','Hyresintäkter, lokal','income','25'],
    ['3912','Hyresintäkter, bostäder','income','0'],
    ['3920','Provisionsintäkter','income','25'],
    ['3930','Licensintäkter och royalties','income','25'],
    ['3940','Bidrag och stöd','income','0'],
    ['3950','Återvunna kundfordringar','income',NULL],
    ['3960','Valutakursvinster','income',NULL],
    ['3970','Vinst vid avyttring materiella anläggningstillgångar','income',NULL],
    ['3971','Vinst vid avyttring immateriella anläggningstillgångar','income',NULL],
    ['3972','Vinst vid avyttring finansiella anläggningstillgångar','income',NULL],
    ['3980','Erhållna offentliga stöd/bidrag','income','0'],
    ['3985','Erhållna EU-bidrag','income','0'],
    ['3988','Erhållna skadestånd','income',NULL],
    ['3990','Övriga ersättningar och intäkter','income','25'],

    -- ========== Klass 4: Varuinköp ==========
    ['4010','Inköp varor och material','expense','25'],
    ['4011','Inköp varor 25%','expense','25'],
    ['4012','Inköp varor 12%','expense','12'],
    ['4013','Inköp varor momsfri','expense','0'],
    ['4040','Inköp varor inom EU','expense','25'],
    ['4045','Inköp tjänster EU omvänd moms','expense','25'],
    ['4050','Inköp varor utanför EU','expense','25'],
    ['4055','Inköp tjänster utanför EU','expense','25'],
    ['4100','Inköp råvaror och förnödenheter','expense','25'],
    ['4200','Inköp halvfabrikat','expense','25'],
    ['4300','Inköp handelsvaror','expense','25'],
    ['4400','Inköp underleverantörer','expense','25'],
    ['4500','Övriga inköp','expense','25'],
    ['4510','Import','expense','25'],
    ['4531','Tull','expense',NULL],
    ['4532','Spedition','expense','25'],
    ['4535','Frakter','expense','25'],
    ['4600','Legoarbeten','expense','25'],
    ['4700','Förändring av lager','expense',NULL],
    ['4900','Övriga kostnader för sålda varor','expense','25'],
    ['4910','Förändring pågående arbeten','expense',NULL],
    ['4920','Lagerförändringar','expense',NULL],
    ['4960','Valutakursförluster varuinköp','expense',NULL],
    ['4970','Inkurans','expense',NULL],
    ['4990','Övriga lagerjusteringar','expense',NULL],

    -- ========== Klass 5: Lokalkostnader ==========
    ['5010','Lokalhyra','expense','25'],
    ['5011','Hyra för kontorslokaler','expense','25'],
    ['5012','Hyra för lagerlokaler','expense','25'],
    ['5013','Hyra för produktionslokaler','expense','25'],
    ['5020','El för lokaler','expense','25'],
    ['5030','Värme','expense','25'],
    ['5040','Vatten och avlopp','expense','25'],
    ['5050','Lokaltillbehör','expense','25'],
    ['5060','Städning och renhållning','expense','25'],
    ['5070','Reparation och underhåll av lokaler','expense','25'],
    ['5090','Övriga lokalkostnader','expense','25'],
    ['5100','Fastighetskostnader','expense','25'],
    ['5110','Tomträttsavgäld/arrende','expense','25'],
    ['5120','Reparation och underhåll fastighet','expense','25'],
    ['5130','Fastighetsskatt','expense',NULL],
    ['5170','Fastighetsskötsel och förvaltning','expense','25'],
    ['5190','Övriga fastighetskostnader','expense','25'],
    ['5200','Hyra av anläggningstillgångar','expense','25'],
    ['5210','Hyra/leasing av maskiner','expense','25'],
    ['5220','Hyra/leasing av inventarier','expense','25'],
    ['5250','Hyra/leasing av datorer','expense','25'],
    ['5260','Hyra/leasing av bilar','expense','25'],
    ['5290','Övriga hyreskostnader','expense','25'],

    -- ========== Klass 6: Övriga externa kostnader ==========
    ['6010','Kontorsmateriel','expense','25'],
    ['6040','Förbrukningsinventarier','expense','25'],
    ['6050','Förbrukningsmaterial','expense','25'],
    ['6055','Förbrukningsemballage','expense','25'],
    ['6060','Sjukvård och läkemedel','expense','0'],
    ['6070','Representation','expense','25'],
    ['6071','Representation avdragsgill','expense','25'],
    ['6072','Representation ej avdragsgill','expense',NULL],
    ['6080','Personalfester','expense','25'],
    ['6090','Övriga förbrukningskostnader','expense','25'],
    ['6100','Kontorsmaterial och trycksaker','expense','25'],
    ['6110','Kontorsmaterial','expense','25'],
    ['6150','Trycksaker','expense','25'],
    ['6200','Tele och post','expense','25'],
    ['6210','Telekommunikation','expense','25'],
    ['6211','Telefon','expense','25'],
    ['6212','Mobiltelefon','expense','25'],
    ['6214','Bredband/internet','expense','25'],
    ['6230','Datakommunikation','expense','25'],
    ['6250','Postbefordran','expense','0'],
    ['6300','Företagsförsäkringar och riskkostnader','expense','0'],
    ['6310','Företagsförsäkringar','expense','0'],
    ['6320','Ansvarsförsäkring','expense','0'],
    ['6340','Lagerförsäkring','expense','0'],
    ['6350','Fordonsförsäkring','expense','0'],
    ['6360','Maskinförsäkring','expense','0'],
    ['6370','Förluster kundfordringar','expense',NULL],
    ['6380','Förluster övriga kortfristiga fordringar','expense',NULL],
    ['6390','Övriga riskkostnader','expense','25'],
    ['6400','Förvaltningskostnader','expense','25'],
    ['6410','Styrelsearvoden','expense',NULL],
    ['6420','Revisionsarvoden','expense','25'],
    ['6421','Revision','expense','25'],
    ['6422','Rådgivning, revisionsbolag','expense','25'],
    ['6430','Management fee','expense','25'],
    ['6440','Juridiska konsultarvoden','expense','25'],
    ['6450','Konsultarvoden, övriga','expense','25'],
    ['6460','Redovisningstjänster','expense','25'],
    ['6490','Övriga förvaltningskostnader','expense','25'],
    ['6500','Övriga externa tjänster','expense','25'],
    ['6510','IT-tjänster','expense','25'],
    ['6520','Rekryteringstjänster','expense','25'],
    ['6530','Företagshälsovård','expense','0'],
    ['6540','Bevakningstjänster','expense','25'],
    ['6550','Konsulttjänster','expense','25'],
    ['6560','Serviceavgifter','expense','25'],
    ['6570','Bankkostnader','expense','0'],
    ['6580','Advokat- och rättegångskostnader','expense','25'],
    ['6590','Övriga externa tjänster','expense','25'],
    -- 67xx RESEKOSTNADER (NYTT - saknades helt!)
    ['6700','Resekostnader','expense','25'],
    ['6710','Biljetter','expense','6'],
    ['6711','Flygresor','expense','6'],
    ['6712','Tågresor','expense','6'],
    ['6720','Hotell och logi','expense','12'],
    ['6730','Hyrbilskostnader','expense','25'],
    ['6740','Taxi','expense','6'],
    ['6750','Parkeringskostnader','expense','25'],
    ['6760','Bom- och broavgifter','expense','25'],
    ['6770','Drivmedel tjänsteresor','expense','25'],
    ['6790','Övriga resekostnader','expense','25'],
    -- 68xx Inhyrd personal
    ['6800','Inhyrd personal','expense','25'],
    -- 69xx Övriga externa kostnader
    ['6900','Övriga externa kostnader','expense','25'],
    ['6910','Licensavgifter','expense','25'],
    ['6911','Programvarulicenser/SaaS','expense','25'],
    ['6920','Patentavgifter','expense','25'],
    ['6930','Reklamkostnader','expense','25'],
    ['6940','Marknadsföring','expense','25'],
    ['6941','Google Ads/online-annonsering','expense','25'],
    ['6942','Sociala medier/marknadsföring','expense','25'],
    ['6950','Mässor och utställningar','expense','25'],
    ['6970','Tidningar, facklitteratur','expense','6'],
    ['6980','Föreningsavgifter','expense','0'],
    ['6981','Branschföreningsavgifter','expense','0'],
    ['6990','Övriga externa kostnader','expense','25'],

    -- ========== Klass 7: Personal och avskrivningar ==========
    ['7010','Löner tjänstemän','expense',NULL],
    ['7011','Löner, kollektivanställda','expense',NULL],
    ['7012','Timlöner','expense',NULL],
    ['7013','Ackordslöner','expense',NULL],
    ['7014','Provisionslöner','expense',NULL],
    ['7015','Lön vid sjukdom','expense',NULL],
    ['7016','Lön vid semester','expense',NULL],
    ['7018','Sjuklön','expense',NULL],
    ['7019','Övriga löner','expense',NULL],
    ['7030','Tantiem och bonus','expense',NULL],
    ['7082','Semesterlön','expense',NULL],
    ['7083','Förändring semesterlöneskuld','expense',NULL],
    ['7090','Förändring av semesterskuld','expense',NULL],
    ['7200','Löner VD och styrelse','expense',NULL],
    ['7210','Löner VD','expense',NULL],
    ['7220','Styrelsearvoden','expense',NULL],
    ['7290','Övriga löner till VD/styrelse','expense',NULL],
    ['7310','Kontanta extraersättningar','expense',NULL],
    ['7320','Traktamenten skattefria','expense',NULL],
    ['7321','Traktamenten skattepliktiga','expense',NULL],
    ['7322','Bilersättningar skattefria','expense',NULL],
    ['7323','Bilersättningar skattepliktiga','expense',NULL],
    ['7330','Bilförmån','expense',NULL],
    ['7331','Kostförmån fria måltider','expense',NULL],
    ['7332','Kostförmån','expense',NULL],
    ['7333','Bostadsförmån','expense',NULL],
    ['7340','Lunchkuponger','expense',NULL],
    ['7350','Sjuk- och hälsovård','expense','0'],
    ['7370','Friskvård','expense','0'],
    ['7380','Kostnader för förmåner','expense',NULL],
    ['7381','Personalrepresentation','expense','25'],
    ['7382','Utbildning','expense','25'],
    ['7383','Kurser och konferenser','expense','25'],
    ['7385','Personalfester','expense','25'],
    ['7386','Personalaktiviteter','expense','25'],
    ['7390','Övriga personalkostnader','expense',NULL],
    ['7400','Pensionskostnader','expense',NULL],
    ['7410','Pensionsförsäkringspremier','expense',NULL],
    ['7411','Premiepension','expense',NULL],
    ['7412','ITP-premier','expense',NULL],
    ['7420','Pensionsstiftelse','expense',NULL],
    ['7430','Avdragsgilla pensionskostnader','expense',NULL],
    ['7490','Övriga pensionskostnader','expense',NULL],
    ['7510','Arbetsgivaravgifter','expense',NULL],
    ['7511','Sociala avgifter löner','expense',NULL],
    ['7512','Sociala avgifter semester','expense',NULL],
    ['7530','Särskild löneskatt','expense',NULL],
    ['7533','Särskild löneskatt pensionskostnader','expense',NULL],
    ['7550','Avtalade sociala avgifter','expense',NULL],
    ['7570','Premier för arbetsmarknadsförsäkringar','expense',NULL],
    ['7580','Grupplivförsäkring','expense',NULL],
    ['7610','Utbildning','expense','25'],
    ['7620','Sjuk- och hälsovård','expense','0'],
    ['7631','Personalrepresentation avdragsgill','expense','25'],
    ['7632','Personalrepresentation ej avdragsgill','expense',NULL],
    ['7690','Övriga personalkostnader','expense',NULL],
    -- Nedskrivningar & avskrivningar
    ['7710','Nedskrivningar immateriella tillgångar','expense',NULL],
    ['7720','Nedskrivningar byggnader och mark','expense',NULL],
    ['7730','Nedskrivningar maskiner och inventarier','expense',NULL],
    ['7740','Nedskrivningar finansiella anläggningstillgångar','expense',NULL],
    ['7810','Avskrivningar immateriella tillgångar','expense',NULL],
    ['7820','Avskrivningar byggnader','expense',NULL],
    ['7830','Avskrivningar maskiner och inventarier','expense',NULL],
    ['7832','Avskrivningar inventarier','expense',NULL],
    ['7834','Avskrivningar bilar','expense',NULL],
    ['7835','Avskrivningar datorer','expense',NULL],
    ['7840','Avskrivningar förbättringsutgifter','expense',NULL],

    -- ========== Klass 8: Finansiella poster och skatt ==========
    ['8010','Ränteintäkter koncernföretag','income',NULL],
    ['8020','Ränteintäkter intresseföretag','income',NULL],
    ['8110','Utdelning på andelar koncernföretag','income',NULL],
    ['8120','Utdelning på andelar intresseföretag','income',NULL],
    ['8130','Resultatandelar intresseföretag','income',NULL],
    ['8210','Ränteintäkter bank','income',NULL],
    ['8220','Ränteintäkter kundfordringar','income',NULL],
    ['8230','Ränteintäkter skattemyndigheten','income',NULL],
    ['8290','Övriga finansiella intäkter','income',NULL],
    ['8300','Ränteintäkter, övriga','income',NULL],
    ['8310','Ränteintäkter','income',NULL],
    ['8330','Valutakursvinster finansiella poster','income',NULL],
    ['8340','Utdelningar','income',NULL],
    ['8350','Resultat vid försäljning av värdepapper','income',NULL],
    ['8390','Övriga finansiella intäkter','income',NULL],
    ['8410','Räntekostnader koncernföretag','expense',NULL],
    ['8420','Räntekostnader intresseföretag','expense',NULL],
    ['8510','Räntekostnader bank','expense',NULL],
    ['8520','Räntekostnader leverantörsskulder','expense',NULL],
    ['8530','Räntekostnader skattemyndigheten','expense',NULL],
    ['8540','Räntekostnader övriga skulder','expense',NULL],
    ['8570','Bankavgifter','expense','0'],
    ['8580','Dröjsmålsräntor','expense',NULL],
    ['8590','Övriga finansiella kostnader','expense',NULL],
    ['8610','Valutakursförluster finansiella poster','expense',NULL],
    ['8710','Extraordinära intäkter','income',NULL],
    ['8750','Erhållna koncernbidrag','income',NULL],
    ['8760','Lämnade koncernbidrag','expense',NULL],
    ['8810','Förändring periodiseringsfond','expense',NULL],
    ['8820','Förändring överavskrivningar','expense',NULL],
    ['8830','Förändring övriga obeskattade reserver','expense',NULL],
    ['8850','Återföring periodiseringsfond','income',NULL],
    ['8910','Skatt på årets resultat','expense',NULL],
    ['8920','Uppskjuten skatt','expense',NULL],
    ['8990','Resultat','expense',NULL],
    ['8999','Årets resultat','equity',NULL]
  ];
  v_rec text[];
BEGIN
  FOREACH v_rec SLICE 1 IN ARRAY v_accounts LOOP
    INSERT INTO public.chart_of_accounts (company_id, account_number, account_name, account_type, is_active, vat_code)
    VALUES (p_company_id, v_rec[1], v_rec[2], v_rec[3], true, NULLIF(v_rec[4], ''))
    ON CONFLICT DO NOTHING;
    v_count := v_count + 1;
  END LOOP;
  
  RETURN v_count;
END;
$$;

-- Update VAT codes on existing accounts for all companies
UPDATE chart_of_accounts SET vat_code = '25' WHERE account_number IN ('3010','3040','3050','3060','3100','3200','3500','3510','3520','3590','3600','3610','3620','3690','3900','3910','3920','3990') AND vat_code IS NULL;
UPDATE chart_of_accounts SET vat_code = '12' WHERE account_number IN ('3011','3041','6720') AND vat_code IS NULL;
UPDATE chart_of_accounts SET vat_code = '6' WHERE account_number IN ('3012','3042','6710','6711','6712','6740','6970') AND vat_code IS NULL;
UPDATE chart_of_accounts SET vat_code = '0' WHERE account_number IN ('3013','3043','3300','3305','3310','3400','3980','6060','6250','6300','6310','6320','6340','6350','6360','6530','6570','6980','7350','7370','7620','8570') AND vat_code IS NULL;
UPDATE chart_of_accounts SET vat_code = '25' WHERE account_number IN ('4010','4040','4050','4100','4200','4300','4400','4500','4510','4532','4535','4600','4900','5010','5020','5030','5040','5050','5060','5070','5090','5100','5110','5120','5170','5190','5200','5210','5220','5250','5260','5290') AND vat_code IS NULL;
UPDATE chart_of_accounts SET vat_code = '25' WHERE account_number IN ('6010','6040','6050','6070','6071','6090','6100','6110','6150','6200','6210','6211','6212','6214','6230','6390','6400','6420','6430','6440','6450','6460','6490','6500','6510','6520','6540','6550','6560','6580','6590','6800','6900','6910','6920','6930','6940','6990') AND vat_code IS NULL;
UPDATE chart_of_accounts SET vat_code = '25' WHERE account_number IN ('7381','7382','7385','7610','7631') AND vat_code IS NULL;

-- Seed expanded accounts for all existing companies
DO $$
DECLARE
  comp RECORD;
BEGIN
  FOR comp IN SELECT id FROM companies LOOP
    PERFORM public.seed_bas_2026_accounts(comp.id);
  END LOOP;
END;
$$;

-- Add unique constraint for account_number per company (if not exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'chart_of_accounts_company_account_unique'
  ) THEN
    ALTER TABLE chart_of_accounts ADD CONSTRAINT chart_of_accounts_company_account_unique UNIQUE (company_id, account_number);
  END IF;
END;
$$;
